import { DEFAULT_VJ_PATH_SPEED, type RendererSyncSource } from "@refrct/core";

/** Starting point for hero art direction; tweak in dev, then copy into `lockedHeroPreset.ts`. */
export function createDefaultHeroSync(): RendererSyncSource {
  return {
    bgHex: "#120808",
    blobSize: 0.24,
    pauseAnimation: false,
    blobSpeed: 0.85,
    waveFreq: 5,
    waveAmp: 0.16,
    refract: 0.14,
    edgeSoft: 0.012,
    frostBlur: 2,
    blurQuality: 1,
    chroma: 0.06,
    shapeMode: 0,
    filterMode: 0,
    filterStrength: 0,
    filterScale: 0.5,
    filterMotionSpeed: 1,
    blobCenterX: 0.5,
    blobCenterY: 0.5,
    bloomStrength: 0,
    bloomRadius: 0.2,
    bloomThreshold: 0.88,
    svgSourceUrl: "/blod-wordmark.svg",
    svgTintMode: "original",
    svgTintHex: "#ffffff",
    micDrivingRefraction: false,
    micRefractBoost: 0.65,
    micEnvelope: 0,
    vjMode: false,
    vjDupVertical: false,
    vjDupGap: 0,
    vjDupHorizStep: 0.03,
    vjDupScrollSpeed: 0.11,
    vjPathScale: 1,
    vjPathSpeed: DEFAULT_VJ_PATH_SPEED,
    youtubeEmbedActive: false,
    vjGlassGradeMode: "off",
    vjGlassNeonAHex: "#ff00ee",
    vjGlassNeonBHex: "#1a0055",
    vjGlassGradeIntensity: 0,
    detailDistortionEnabled: true,
    detailDistortionStrength: 0.55,
    detailDistortionScale: 3.2,
    detailDirtStrength: 0.4,
    detailDirtHex: "#665648",
    lensMouseInput: false,
    fluidDensity: 0.45,
  };
}
